welcome:
  message : Welcome to dev environment, sudheer pawar

        
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
  h2: 
    console:
      enabled: true
